apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic-prod

bases:
  - ../../base

resources:
  - namespace.yaml
  - petclinic-deployment.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/petclinic-prod/petclinic-app
    newTag: petclinic-prod
